### ISSUE TITLE
Please make the side bar fixed 

### ISSUE THREAD

**Issue by oz123** [pallets/flask-sphinx-themes#10]
This way we don't have to scroll up every time...
This is especially trough to project with really long docs like flask, but it 
also been an issue while reading the docs for click.

Simple add to flasky.css, 
```
div.sphinxsidebarwrapper {
    padding: 18px 10px;
    position: fixed;
    word-wrap: break-word;
    width: 10%;

}
```

this makes it really nice to read.

If you want, I can make a PR.

**Comment by davidism** [comment]
This breaks if the sidebar is taller than the window.  If you can figure out how Sphinx or SQLAlchemy do it and add it is as an option that's welcome.
